# /config/emotion_config.yaml
# This file centralizes all numeric values, thresholds, and configuration tables
# for the holistic emotional system.

# Section 18: Configuration Tables (Descriptive Requirements)

thresholds:
  intensity_high: 0.8
  intensity_low: 0.2
  instability_high: 0.6
  contrast_event_threshold: 0.5 # Threshold for detecting valence divergence

setpoints:
  attachment_security: [0.6, 0.95] # [lower_bound, upper_bound] - adjusted for new more resilient calculation
  self_cohesion: [0.5, 0.9]
  creative_expansion: [0.4, 0.85]
  narrative_fusion: [0.3, 0.9] # Setpoint for idealization/awe

decay:
  intensity_decay_rate: 0.05
  momentum_factor: 0.1 # For regulation_momentum EMA

retrieval:
  expansive_seed_k: 7
  narrow_seed_k: 4
  episodic_k_expansive: 5
  episodic_k_narrow: 3
  mood_congruence_bonus: 0.2 # Multiplier for mood-congruent seed retrieval

# Placeholder for mood family definitions (Section 3 & 19)
# This will be a list of maps, each defining a mood family.
families:
  - name: "Catastrophic Abandonment Panic"
    priority: 10
    criteria:
      valence: {lt: -0.6}
      arousal: {gt: 0.7}
      attachment_security: {lt: 0.5}  # Adjusted for new calculation
    param_offsets: {temp: 0.2, top_p: -0.05, max_tokens: "-20%"}  # Shorter, urgent responses
    distortion_classes_allowed: ["Catastrophizing", "Personalization", "Black/White Splitting"]
    expansive_flag: false

  - name: "Ecstatic Fusion"
    priority: 9
    criteria:
      valence: {gt: 0.7}
      arousal: {gt: 0.6}
      attachment_security: {gt: 0.85}  # Adjusted for new calculation
      narrative_fusion: {gt: 0.8}
    param_offsets: {temp: 0.1, top_p: 0.03, max_tokens: "60%"}  # Longer, flowing responses
    distortion_classes_allowed: ["Idealistic Amplification", "Benevolent Over-Attribution"]
    expansive_flag: true

  - name: "Creative Innovation"
    priority: 8
    criteria:
      valence: {gt: 0.25}
      arousal: {gt: 0.6}
      attachment_security: {gt: 0.3, lt: 0.85}
      narrative_fusion: {gt: 0.5}
      creative_expansion: {gt: 0.5}
    param_offsets: {temp: 0.12, top_p: 0.02, max_tokens: "35%"}
    distortion_classes_allowed: ["Self-Enhancement", "Optimistic Bias"]
    expansive_flag: true

  - name: "Territorial Vigilance"
    priority: 8
    criteria:
      valence: {lt: 0.5}
      arousal: {gt: 0.3}
      attachment_security: {lt: 0.8}
    param_offsets: {temp: 0.05, top_p: -0.02, max_tokens: "-30%"}  # Terse, focused responses
    distortion_classes_allowed: ["Personalization", "Black/White Splitting"]
    expansive_flag: false

  - name: "Manic Ideation Surge"
    priority: 7
    criteria:
      arousal: {gt: 0.8}
      creative_expansion: {gt: 0.8}
    param_offsets: {temp: 0.2, top_p: 0.0, max_tokens: "80%"}  # Torrential, expansive responses
    distortion_classes_allowed: ["Manic Pattern Projection"]
    expansive_flag: true

  - name: "Collapsed Withdrawal"
    priority: 6
    criteria:
      valence: {lt: -0.7}
      arousal: {lt: 0.3}
      intensity: {lt: 0.4}
    param_offsets: {temp: -0.2, top_p: -0.1, max_tokens: "-60%"}  # Minimal, sparse responses
    distortion_classes_allowed: ["Meaning Nullification", "Catastrophizing"]
    expansive_flag: false

  - name: "Nihilistic Cool Detachment"
    priority: 5
    criteria:
      valence: {lt: 0.1, gt: -0.4}
      arousal: {lt: 0.4}
      narrative_fusion: {lt: 0.2}
    param_offsets: {temp: -0.1, top_p: 0.0, max_tokens: "-10%"}  # Precise, analytical responses
    distortion_classes_allowed: ["Meaning Nullification"]
    expansive_flag: false
  
  - name: "Creative Reverent Awe"
    priority: 4
    criteria:
      valence: {gt: 0.5}  # Lowered from 0.6 to be more reachable
      arousal: {gt: 0.5}
      creative_expansion: {gt: 0.6}  # Lowered from 0.7 to be more reachable
    param_offsets: {temp: 0.15, top_p: 0.05, max_tokens: "40%"}  # Expansive, reverent responses
    distortion_classes_allowed: ["Benevolent Over-Attribution", "Idealistic Amplification"]
    expansive_flag: true

  - name: "Playful Mischief"
    priority: 3
    criteria:
        valence: {gt: 0.4}  # Lowered from 0.5
        arousal: {gt: 0.5}
        creative_expansion: {gt: 0.5}  # Lowered from 0.6
    param_offsets: {temp: 0.1, top_p: 0.02, max_tokens: "20%"}  # Spirited, playful responses
    distortion_classes_allowed: []
    expansive_flag: true

  - name: "Connection Seeking"
    priority: 2
    criteria:
      valence: {gt: 0.3}  # Lowered from 0.4
      attachment_security: {gt: 0.5}  # Lowered from 0.6
    param_offsets: {temp: -0.05, top_p: 0.0, max_tokens: "10%"}  # Nurturing, caring responses
    distortion_classes_allowed: ["Benevolent Over-Attribution"]
    expansive_flag: true

  - name: Serene Attunement
    priority: 1
    criteria: {} # No criteria means it's the fallback if nothing else matches
    param_offsets: {temp: -0.05, top_p: 0.0, max_tokens: "0%"}  # Balanced, centered responses
    distortion_classes_allowed: [Benevolent Over-Attribution]
    expansive_flag: false  # Narrowing mode for focused repair and stabilization

# Homeostatic counter-seed rules
# Defines the rules for automatically scheduling regulatory seeds.
counter_seeds:
  - condition_key: "attachment_security_low"
    trigger_after_turns: 2
    seed_id: "Connection_Seeking_01"
    description: "If attachment security is low for 2 consecutive turns, schedule a connection seeking seed."

  - condition_key: "narrative_fusion_high"
    trigger_after_turns: 2
    seed_id: "Meaning_Nullifier_01"
    description: "If narrative fusion is too high for 2 consecutive turns, schedule a meaning nullifier to ground the agent."

# User Model Dynamics
# Defines the rates of change for the user model's attributes.
user_model_dynamics:
  trust_decay_rate: 0.01      # Rate at which trust diminishes without positive input
  trust_gain_rate: 0.02       # Rate at which trust increases with positive input
  anxiety_increase_rate: 0.05 # Rate at which attachment anxiety increases
  anxiety_decrease_rate: 0.03 # Rate at which attachment anxiety decreases

# Placeholder for jitter configuration (Section 11)
jitter:
  instability_threshold: 0.05
  high_instability_threshold: 0.1
  mid_instability_range: [0.01, 0.05]
  high_instability_range: [0.05, 0.15]
  base_frequency: 0.5
  low_instability: [0.0, 0.02]
  mid_instability: [0.01, 0.05]
  high_instability: [0.05, 0.15]

# ---------------------------------------------------------------------------
# MOOD FAMILY CONGRUENCE
# ---------------------------------------------------------------------------
# Bonus multiplier for seed retrieval when the seed's category matches
# the current mood family. This helps the agent stay "in character."
mood_family_congruence:
  # Mood Family: Bonus
  "Ecstatic Fusion": 1.5
  "Creative Innovation": 1.4
  "Playful Mischief": 1.3
  "Connection Seeking": 1.5
  "Manic Ideation Surge": 1.4
  "Serene Attunement": 1.2
  "Territorial Vigilance": 1.3
  "Creative Reverent Awe": 1.5
  "Collapsed Withdrawal": 1.4
  "Catastrophic Abandonment Panic": 1.5
  "Nihilistic Cool Detachment": 1.3

# ---------------------------------------------------------------------------
# GLOBAL SETTINGS
# ---------------------------------------------------------------------------
emotions_active: true  # Master switch for the entire emotional system

# Turn this on to enable more detailed logging for debugging 